CREATE SEQUENCE SGCAM_MAPA.SQ_REPRESENTANTE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOORDER
NOCACHE;

CREATE SEQUENCE SGCAM_MAPA.SQ_CAMARA
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOORDER
NOCACHE;

CREATE SEQUENCE SGCAM_MAPA.SQ_ENTIDADE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE
NOORDER
NOCACHE;

CREATE TABLE SGCAM_MAPA.S_REPRESENTANTE(
	ID_REPRESENTANTE NUMBER(10) NOT NULL,
	NM_NOME VARCHAR(250) NOT NULL,
	DS_EMAIL VARCHAR(250),
	NR_CPF CHAR(11) NOT NULL UNIQUE,
	DS_BUSCA_NOME_EMAIL_CPF VARCHAR(600),
	CONSTRAINT PK_REPRESENTANTE PRIMARY KEY (ID_REPRESENTANTE)
);
CREATE INDEX IAD_REPRESENTANTE_NM_NOME ON S_REPRESENTANTE(NM_NOME);
CREATE INDEX IAD_REPRESENTANTE_DS_EMAIL ON S_REPRESENTANTE(DS_EMAIL);
CREATE INDEX IAD_REPRESENTANTE_DS_BUSCA ON S_REPRESENTANTE(DS_BUSCA_NOME_EMAIL_CPF);
--
-- Comments goes here
--
 COMMENT ON TABLE SGCAM_MAPA.S_REPRESENTANTE IS
'Armazena informações da Representante';

COMMENT ON COLUMN SGCAM_MAPA.S_REPRESENTANTE.ID_REPRESENTANTE IS
'Identificador único do registro';

COMMENT ON COLUMN SGCAM_MAPA.S_REPRESENTANTE.NM_NOME IS
'Nome do representanteVW';

COMMENT ON COLUMN SGCAM_MAPA.S_REPRESENTANTE.DS_EMAIL IS
'Email do representanteVW';

COMMENT ON COLUMN SGCAM_MAPA.S_REPRESENTANTE.NR_CPF IS
'CPF do representanteVW';

COMMENT ON COLUMN SGCAM_MAPA.S_REPRESENTANTE.DS_BUSCA_NOME_EMAIL_CPF IS
'Campo que contem o nome, email e cpf para realizar a busca';


CREATE TABLE SGCAM_MAPA.S_CAMARA(
	ID_CAMARA NUMBER(10) NOT NULL,
	NM_NOME VARCHAR(256) NOT NULL,
	NM_NOMECLATURA VARCHAR(100) NOT NULL,
	CD_TIPO_CAMARA NUMBER(1) NOT NULL CONSTRAINT CK_CAMARA_CD_TIPO_CAMARA CHECK( CD_TIPO_CAMARA IN(1,2) ),
	CD_TIPO_SITUACAO_CAMARA NUMBER(1) NOT NULL CONSTRAINT CK_CAMARA_CD_TP_SITU_CAMARA CHECK( CD_TIPO_SITUACAO_CAMARA IN(1,2) ),
	DH_CRIACAO_REGISTRO TIMESTAMP NOT NULL,
	ID_REPRESENT_SECRETARIO NUMBER(10) NOT NULL,
	ID_REPRESENT_SUPERVISOR NUMBER(10),
	ID_REPRESENT_CONSULTOR_TECNICO NUMBER(10),
	ID_REPRESENT_PRESIDENTE NUMBER(10),

	CONSTRAINT PK_CAMARA PRIMARY KEY (ID_CAMARA),
	CONSTRAINT FK_CAMARA_REPRESENT_SECRETARIO FOREIGN KEY (ID_REPRESENT_SECRETARIO) REFERENCES SGCAM_MAPA.S_REPRESENTANTE(ID_REPRESENTANTE),
	CONSTRAINT FK_CAMARA_REPRESENT_SUPERVISOR FOREIGN KEY (ID_REPRESENT_SUPERVISOR) REFERENCES SGCAM_MAPA.S_REPRESENTANTE(ID_REPRESENTANTE),
	CONSTRAINT FK_CAMARA_REPRESENT_CONSU_TEC FOREIGN KEY (ID_REPRESENT_CONSULTOR_TECNICO) REFERENCES SGCAM_MAPA.S_REPRESENTANTE(ID_REPRESENTANTE),
	CONSTRAINT FK_CAMARA_REPRESENT_PRESIDENTE FOREIGN KEY (ID_REPRESENT_PRESIDENTE) REFERENCES SGCAM_MAPA.S_REPRESENTANTE(ID_REPRESENTANTE)
);
--
-- Comments goes here
--
 COMMENT ON TABLE SGCAM_MAPA.S_CAMARA IS
'Armazena informações da câmara';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.ID_CAMARA IS
'Identificador único da câmara';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.NM_NOME IS
'Nome da câmara';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.NM_NOMECLATURA IS
'Nomeclatura da câmara';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.CD_TIPO_CAMARA IS
'Identifcador do tipo da câmara . Valores válidos: (1 = Setorial, 2 = Temática)';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.CD_TIPO_SITUACAO_CAMARA IS
'Identifcador da situação da câmara . Valores válidos: (1 = Inativo, 2 = Ativo)';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.DH_CRIACAO_REGISTRO IS
'Data e hora da criação do registro';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.ID_REPRESENT_SECRETARIO IS
'Identificador do representanteVW como secretário';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.ID_REPRESENT_SUPERVISOR IS
'Identificador do representanteVW como supervisor';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.ID_REPRESENT_CONSULTOR_TECNICO IS
'Identificador do representanteVW como consultor técnico';

COMMENT ON COLUMN SGCAM_MAPA.S_CAMARA.ID_REPRESENT_PRESIDENTE IS
'Identificador do representanteVW como presidente';


CREATE TABLE SGCAM_MAPA.S_ENTIDADE(
	ID_ENTIDADE NUMBER(10) NOT NULL,
	NM_NOME VARCHAR(256) NOT NULL,
	NM_SIGLA VARCHAR(100) NOT NULL,
	NM_TITULAR VARCHAR(100) NOT NULL,
	DH_CRIACAO_REGISTRO TIMESTAMP NOT NULL,

	CONSTRAINT PK_ENTIDADE PRIMARY KEY (ID_ENTIDADE)
);
CREATE INDEX IAD_ENTIDADE_NM_NOME ON S_ENTIDADE(NM_NOME);
CREATE INDEX IAD_ENTIDADE_NM_SIGLA ON S_ENTIDADE(NM_SIGLA);
--
-- Comments goes here
--
 COMMENT ON TABLE SGCAM_MAPA.S_ENTIDADE IS
'Armazena informações da Entidade';

COMMENT ON COLUMN SGCAM_MAPA.S_ENTIDADE.ID_ENTIDADE IS
'Identificador único do registro';

COMMENT ON COLUMN SGCAM_MAPA.S_ENTIDADE.NM_NOME IS
'Nome da Entidade';

COMMENT ON COLUMN SGCAM_MAPA.S_ENTIDADE.NM_SIGLA IS
'Sigla da câmara';

COMMENT ON COLUMN SGCAM_MAPA.S_ENTIDADE.NM_TITULAR IS
'Nome do titular da entidade';

COMMENT ON COLUMN SGCAM_MAPA.S_ENTIDADE.DH_CRIACAO_REGISTRO IS
'Data e hora da criação do registro';
