GET http://localhost:8080/abcom_api/api/v1/referencial
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDg2NjIzMjE0MSIsInRpcG9QZXNzb2EiOiJGIiwiYXRpdm8iOnRydWUsImVzdHJhbmdlaXJvIjpmYWxzZSwiYXBsaWNhY29lcyI6WzQ1Myw0OTQsMTA1NTQsMSwxMDU1M10sImlkVXN1YXJpbyI6OTEzNTA0LCJpcCI6IjEyNy4wLjAuMSIsImlzcyI6ImJyLmdvdi5tYXBhIiwiZG9jdW1lbnRvIjoiMDA4NjYyMzIxNDEiLCJub21lIjoiRGFuaWVsIEFsdmVzIEluYWNpbyBEaSBBcmF1am8iLCJncnVwb3MiOls4NTAsODUxLDE1Nzk0LDkxMCw4NTgsODQ5LDIwLDE1ODEyXSwiZGVSZW

###

POST http://localhost:8080/abcom_api/api/v1/referencial
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDg2NjIzMjE0MSIsInRpcG9QZXNzb2EiOiJGIiwiYXRpdm8iOnRydWUsImVzdHJhbmdlaXJvIjpmYWxzZSwiYXBsaWNhY29lcyI6WzQ1Myw0OTQsMTA1NTQsMSwxMDU1M10sImlkVXN1YXJpbyI6OTEzNTA0LCJpcCI6IjEyNy4wLjAuMSIsImlzcyI6ImJyLmdvdi5tYXBhIiwiZG9jdW1lbnRvIjoiMDA4NjYyMzIxNDEiLCJub21lIjoiRGFuaWVsIEFsdmVzIEluYWNpbyBEaSBBcmF1am8iLCJncnVwb3MiOls4NTAsODUxLDE1Nzk0LDkxMCw4NTgsODQ5LDIwLDE1ODEyXSwiZGVSZW
Content-Type: application/json

{
  "nome": "TESTE NOVO"
}

###

PUT http://localhost:8080/abcom_api/api/v1/referencial/21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDg2NjIzMjE0MSIsInRpcG9QZXNzb2EiOiJGIiwiYXRpdm8iOnRydWUsImVzdHJhbmdlaXJvIjpmYWxzZSwiYXBsaWNhY29lcyI6WzQ1Myw0OTQsMTA1NTQsMSwxMDU1M10sImlkVXN1YXJpbyI6OTEzNTA0LCJpcCI6IjEyNy4wLjAuMSIsImlzcyI6ImJyLmdvdi5tYXBhIiwiZG9jdW1lbnRvIjoiMDA4NjYyMzIxNDEiLCJub21lIjoiRGFuaWVsIEFsdmVzIEluYWNpbyBEaSBBcmF1am8iLCJncnVwb3MiOls4NTAsODUxLDE1Nzk0LDkxMCw4NTgsODQ5LDIwLDE1ODEyXSwiZGVSZW
Content-Type: application/json

{
  "nome": "TESTE NOVO 2",
  "ativo": true
}

###

DELETE http://localhost:8080/abcom_api/api/v1/referencial/21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDg2NjIzMjE0MSIsInRpcG9QZXNzb2EiOiJGIiwiYXRpdm8iOnRydWUsImVzdHJhbmdlaXJvIjpmYWxzZSwiYXBsaWNhY29lcyI6WzQ1Myw0OTQsMTA1NTQsMSwxMDU1M10sImlkVXN1YXJpbyI6OTEzNTA0LCJpcCI6IjEyNy4wLjAuMSIsImlzcyI6ImJyLmdvdi5tYXBhIiwiZG9jdW1lbnRvIjoiMDA4NjYyMzIxNDEiLCJub21lIjoiRGFuaWVsIEFsdmVzIEluYWNpbyBEaSBBcmF1am8iLCJncnVwb3MiOls4NTAsODUxLDE1Nzk0LDkxMCw4NTgsODQ5LDIwLDE1ODEyXSwiZGVSZW

